### ISSUE TITLE
Is the software feature complete?

### ISSUE THREAD

**Issue by davekinkead** [uluturki/social-annotate#23]
> In addition, JOSS requires that software should be feature-complete (i.e. no half-baked solutions) and designed for maintainable extension (not one-off modifications of existing tools). 

The readme states instagram support and V1.0 is coming soon https://github.com/uluturki/social-annotate#going-public-v10-soon.

I can't see surveys on instagram.

Ref https://github.com/openjournals/joss-reviews/issues/2780

**Comment by onurvarol** [comment]
Dear @davekinkead, this tool is extendable to multiple platforms with minimal amount of coding. We updated the Instagram feature as an example, so there are three survey available: twitter-user, twitter-tweet, and instagram-user. Our paper describes how one can extend our tool to other platforms. We also provide a section on how to contribute.
