### ISSUE TITLE
[Update Code Documentation and API Examples]

### ISSUE THREAD

**Issue by sara-02** [uluturki/social-annotate#25]
Hey @onurvarol as a part of the JOSS review we also require the docs to be updated for the following

- [ ] Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

- [ ] Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

Can you please update the same, or share the portion of the repo where the updated information can be found. Best will be hosting the docs on ReadTheDocs, or if you want to host the APIs then Swagger, so that we have examples of the APIs format redily available.

**Comment by onurvarol** [comment]
Dear @sara-02, we updated the README file to provide more details about the software. We also embed a Youtube video with a demo of the tool.
